version: "3.8"
services:
  postgres:
    image: postgres:16.2-bullseye
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
    volumes:
      - '${PV_LOC}/postgres/postgres-data:/var/lib/postgresql'
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2.4
    command: redis-server --save "" --appendonly no
    container_name: redis-grpc
    environment:
      REDIS_PORT: 6379
      REDIS_DATABASES: 16
      REDIS_REPLICATION_MODE: master
    volumes:
      - ${PV_LOC}/redis/data:/data
    restart: always
    ports:
      - "6378:6379"

  zookeeper:
    image: zookeeper:3.9.1-jre-17
    container_name: zookeeper
    volumes:
      - ${PV_LOC}/zk-data:/var/lib/zookeeper/data \
      - ${PV_LOC}/zk-txn-logs:/var/lib/zookeeper/log \

  elasicsearch:
    container_name: elasticsearch
    image: elasticsearch:8.12.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      xpack.security.enabled: false