"""fixing relationships 8

Revision ID: 1409a4c227f1
Revises: 5862dbc65636
Create Date: 2024-03-06 00:15:24.940366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1409a4c227f1"
down_revision: Union[str, None] = "5862dbc65636"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cafes",
        sa.Column(
            "geodata_id",
            sa.String(),
            nullable=True,
        ),
    )
    op.create_unique_constraint(
        None, "cafes", ["geodata_id"]
    )
    op.create_foreign_key(
        None,
        "cafes",
        "geodatas",
        ["geodata_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "cities",
        "country_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.create_unique_constraint(
        None, "geodatas", ["cafe_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "geodatas", type_="unique"
    )
    op.alter_column(
        "cities",
        "country_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_constraint(
        None, "cafes", type_="foreignkey"
    )
    op.drop_constraint(
        None, "cafes", type_="unique"
    )
    op.drop_column("cafes", "geodata_id")
    # ### end Alembic commands ###
