"""created reviews table


Revision ID: 14e65299bde3
Revises: 2e7368ef7617
Create Date: 2024-03-08 18:40:55.597445

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14e65299bde3"
down_revision: Union[str, None] = "2e7368ef7617"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column(
            "rating", sa.Float(), nullable=False
        ),
        sa.Column(
            "title", sa.String(), nullable=False
        ),
        sa.Column(
            "body", sa.String(), nullable=True
        ),
        sa.Column(
            "author", sa.String(), nullable=True
        ),
        sa.Column(
            "cafe_id", sa.String(), nullable=True
        ),
        sa.Column(
            "id", sa.String(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["cafe_id"],
            ["cafes.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reviews")
    # ### end Alembic commands ###
