"""changed company to cafe null

Revision ID: 19cddd1d6642
Revises: f31c0c1f790a
Create Date: 2024-03-06 01:48:10.247902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19cddd1d6642"
down_revision: Union[str, None] = "f31c0c1f790a"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cafes",
        sa.Column(
            "company_id",
            sa.String(),
            nullable=True,
        ),
    )
    op.drop_constraint(
        "cafes_company_name_fkey",
        "cafes",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "cafes",
        "companies",
        ["company_id"],
        ["id"],
    )
    op.drop_column("cafes", "company_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cafes",
        sa.Column(
            "company_name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        None, "cafes", type_="foreignkey"
    )
    op.create_foreign_key(
        "cafes_company_name_fkey",
        "cafes",
        "companies",
        ["company_name"],
        ["name"],
    )
    op.drop_column("cafes", "company_id")
    # ### end Alembic commands ###
