"""fixing relationships 9

Revision ID: 1c4c66a94d41
Revises: 1409a4c227f1
Create Date: 2024-03-06 00:15:48.858659

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c4c66a94d41"
down_revision: Union[str, None] = "1409a4c227f1"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "cafes_geodata_id_key",
        "cafes",
        type_="unique",
    )
    op.drop_constraint(
        "cafes_geodata_id_fkey",
        "cafes",
        type_="foreignkey",
    )
    op.drop_column("cafes", "geodata_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cafes",
        sa.Column(
            "geodata_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "cafes_geodata_id_fkey",
        "cafes",
        "geodatas",
        ["geodata_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        "cafes_geodata_id_key",
        "cafes",
        ["geodata_id"],
    )
    # ### end Alembic commands ###
