"""removed cafe company_name

Revision ID: 262abe040913
Revises: 98d6c92f3364
Create Date: 2024-03-06 01:58:51.027083

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "262abe040913"
down_revision: Union[str, None] = "98d6c92f3364"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "cafes_company_name_fkey",
        "cafes",
        type_="foreignkey",
    )
    op.drop_column("cafes", "company_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cafes",
        sa.Column(
            "company_name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "cafes_company_name_fkey",
        "cafes",
        "companies",
        ["company_name"],
        ["name"],
    )
    # ### end Alembic commands ###
