"""fixing relationships 5

Revision ID: 2fc0e68ce7e7
Revises: 5b1ab55b338c
Create Date: 2024-03-05 23:57:35.739286

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fc0e68ce7e7"
down_revision: Union[str, None] = "5b1ab55b338c"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
