"""creating relationships

Revision ID: 5139721af974
Revises: 52392a724cb2
Create Date: 2024-03-05 23:39:36.335931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5139721af974"
down_revision: Union[str, None] = "52392a724cb2"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cafes",
        sa.Column(
            "company_id",
            sa.String(),
            nullable=False,
        ),
    )
    op.add_column(
        "cafes",
        sa.Column(
            "geodata_id",
            sa.String(),
            nullable=False,
        ),
    )
    op.add_column(
        "cafes",
        sa.Column(
            "menu_id", sa.String(), nullable=True
        ),
    )
    op.add_column(
        "cafes",
        sa.Column(
            "rating_id",
            sa.String(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        None,
        "cafes",
        "ratings",
        ["rating_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "cafes",
        "geodatas",
        ["geodata_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "cafes",
        "menus",
        ["menu_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "cafes",
        "companies",
        ["company_id"],
        ["id"],
    )
    op.add_column(
        "cities",
        sa.Column(
            "country_id",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        None,
        "cities",
        "countries",
        ["country_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "geodatas",
        sa.Column(
            "cafe_id", sa.String(), nullable=True
        ),
    )
    op.add_column(
        "geodatas",
        sa.Column(
            "country_id",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.add_column(
        "geodatas",
        sa.Column(
            "city_id", sa.Integer(), nullable=True
        ),
    )
    op.create_foreign_key(
        None,
        "geodatas",
        "cafes",
        ["cafe_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "geodatas",
        "countries",
        ["country_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "geodatas",
        "cities",
        ["city_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "menu_entries",
        sa.Column(
            "menu_id", sa.String(), nullable=True
        ),
    )
    op.add_column(
        "menu_entries",
        sa.Column(
            "currency_id",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        None,
        "menu_entries",
        "menus",
        ["menu_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "menu_entries",
        "currencies",
        ["currency_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "menus",
        sa.Column(
            "cafe_id", sa.String(), nullable=True
        ),
    )
    op.create_foreign_key(
        None,
        "menus",
        "cafes",
        ["cafe_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "menus", type_="foreignkey"
    )
    op.drop_column("menus", "cafe_id")
    op.drop_constraint(
        None, "menu_entries", type_="foreignkey"
    )
    op.drop_constraint(
        None, "menu_entries", type_="foreignkey"
    )
    op.drop_column("menu_entries", "currency_id")
    op.drop_column("menu_entries", "menu_id")
    op.drop_constraint(
        None, "geodatas", type_="foreignkey"
    )
    op.drop_constraint(
        None, "geodatas", type_="foreignkey"
    )
    op.drop_constraint(
        None, "geodatas", type_="foreignkey"
    )
    op.drop_column("geodatas", "city_id")
    op.drop_column("geodatas", "country_id")
    op.drop_column("geodatas", "cafe_id")
    op.drop_constraint(
        None, "cities", type_="foreignkey"
    )
    op.drop_column("cities", "country_id")
    op.drop_constraint(
        None, "cafes", type_="foreignkey"
    )
    op.drop_constraint(
        None, "cafes", type_="foreignkey"
    )
    op.drop_constraint(
        None, "cafes", type_="foreignkey"
    )
    op.drop_constraint(
        None, "cafes", type_="foreignkey"
    )
    op.drop_column("cafes", "rating_id")
    op.drop_column("cafes", "menu_id")
    op.drop_column("cafes", "geodata_id")
    op.drop_column("cafes", "company_id")
    # ### end Alembic commands ###
