"""creating tables

Revision ID: 52392a724cb2
Revises: 8c1dc60a33bc
Create Date: 2024-03-05 23:38:59.975709

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52392a724cb2"
down_revision: Union[str, None] = "8c1dc60a33bc"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cafes",
        sa.Column(
            "id", sa.String(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cities",
        sa.Column(
            "id", sa.Integer(), nullable=False
        ),
        sa.Column(
            "code", sa.String(), nullable=False
        ),
        sa.Column(
            "name", sa.String(), nullable=False
        ),
        sa.Column(
            "name_ru", sa.String(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("name_ru"),
    )
    op.create_table(
        "companies",
        sa.Column(
            "name", sa.String(), nullable=True
        ),
        sa.Column(
            "description_ru",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "logo", sa.String(), nullable=True
        ),
        sa.Column(
            "id", sa.String(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "countries",
        sa.Column(
            "id", sa.Integer(), nullable=False
        ),
        sa.Column(
            "code", sa.String(), nullable=False
        ),
        sa.Column(
            "name", sa.String(), nullable=False
        ),
        sa.Column(
            "name_ru", sa.String(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("name_ru"),
    )
    op.create_table(
        "currencies",
        sa.Column(
            "id", sa.Integer(), nullable=False
        ),
        sa.Column(
            "code", sa.String(), nullable=False
        ),
        sa.Column(
            "name", sa.String(), nullable=False
        ),
        sa.Column(
            "name_ru", sa.String(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("name_ru"),
    )
    op.create_table(
        "geodatas",
        sa.Column(
            "latitude",
            sa.Numeric(precision=7, scale=4),
            nullable=False,
        ),
        sa.Column(
            "longitude",
            sa.Numeric(precision=7, scale=4),
            nullable=False,
        ),
        sa.Column(
            "street", sa.String(), nullable=True
        ),
        sa.Column(
            "house", sa.String(), nullable=True
        ),
        sa.Column(
            "id", sa.String(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "menu_entries",
        sa.Column(
            "name", sa.String(), nullable=True
        ),
        sa.Column(
            "description_ru",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "price", sa.Float(), nullable=True
        ),
        sa.Column(
            "id", sa.String(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "menus",
        sa.Column(
            "id", sa.String(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ratings",
        sa.Column(
            "stars", sa.Integer(), nullable=False
        ),
        sa.Column(
            "comment", sa.Integer(), nullable=True
        ),
        sa.Column(
            "id", sa.String(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ratings")
    op.drop_table("menus")
    op.drop_table("menu_entries")
    op.drop_table("geodatas")
    op.drop_table("currencies")
    op.drop_table("countries")
    op.drop_table("companies")
    op.drop_table("cities")
    op.drop_table("cafes")
    # ### end Alembic commands ###
