"""fixing relationships 2

Revision ID: 91286ac50ebe
Revises: cb61dc3b0be3
Create Date: 2024-03-05 23:43:10.131770

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "91286ac50ebe"
down_revision: Union[str, None] = "cb61dc3b0be3"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "cafes_menu_id_fkey",
        "cafes",
        type_="foreignkey",
    )
    op.drop_constraint(
        "cafes_rating_id_fkey",
        "cafes",
        type_="foreignkey",
    )
    op.drop_column("cafes", "menu_id")
    op.drop_column("cafes", "rating_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cafes",
        sa.Column(
            "rating_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "cafes",
        sa.Column(
            "menu_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "cafes_rating_id_fkey",
        "cafes",
        "ratings",
        ["rating_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "cafes_menu_id_fkey",
        "cafes",
        "menus",
        ["menu_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
