"""changed company to cafe not null

Revision ID: 98d6c92f3364
Revises: 6b798a917d82
Create Date: 2024-03-06 01:49:58.234992

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98d6c92f3364"
down_revision: Union[str, None] = "6b798a917d82"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cafes",
        sa.Column(
            "company_name",
            sa.String(),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None,
        "cafes",
        "companies",
        ["company_name"],
        ["name"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "cafes", type_="foreignkey"
    )
    op.drop_column("cafes", "company_name")
    # ### end Alembic commands ###
