"""creating indicies

Revision ID: b3043da7ae4c
Revises: 14e65299bde3
Create Date: 2024-03-08 23:35:51.777798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3043da7ae4c"
down_revision: Union[str, None] = "14e65299bde3"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "cities_name_key",
        "cities",
        type_="unique",
    )
    op.create_index(
        op.f("ix_cities_name"),
        "cities",
        ["name"],
        unique=True,
    )
    op.create_index(
        op.f("ix_geodatas_city_id"),
        "geodatas",
        ["city_id"],
        unique=False,
    )
    op.alter_column(
        "reviews",
        "cafe_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reviews",
        "cafe_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_index(
        op.f("ix_geodatas_city_id"),
        table_name="geodatas",
    )
    op.drop_index(
        op.f("ix_cities_name"),
        table_name="cities",
    )
    op.create_unique_constraint(
        "cities_name_key", "cities", ["name"]
    )
    # ### end Alembic commands ###
