"""fixing relationships 3

Revision ID: c645ab551955
Revises: b4de6d2a0d7c
Create Date: 2024-03-05 23:45:22.079899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c645ab551955"
down_revision: Union[str, None] = "b4de6d2a0d7c"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
