"""fixing relationships

Revision ID: cb61dc3b0be3
Revises: 5139721af974
Create Date: 2024-03-05 23:42:40.616875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb61dc3b0be3"
down_revision: Union[str, None] = "5139721af974"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "cafes_geodata_id_fkey",
        "cafes",
        type_="foreignkey",
    )
    op.drop_column("cafes", "geodata_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cafes",
        sa.Column(
            "geodata_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "cafes_geodata_id_fkey",
        "cafes",
        "geodatas",
        ["geodata_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
