"""minor updates

Revision ID: d41959688955
Revises: af4a016e3474
Create Date: 2024-05-15 17:47:54.782147

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d41959688955"
down_revision: Union[str, None] = "af4a016e3474"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "cities_code_key",
        "cities",
        type_="unique",
    )
    op.add_column(
        "companies",
        sa.Column(
            "website", sa.String(), nullable=True
        ),
    )
    op.drop_column("companies", "logo")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column(
            "logo",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("companies", "website")
    op.create_unique_constraint(
        "cities_code_key", "cities", ["code"]
    )
    # ### end Alembic commands ###
