"""fixin roaster

Revision ID: d9d4a24e04d0
Revises: 4b7db39b1f81
Create Date: 2024-03-20 20:30:20.530461

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9d4a24e04d0"
down_revision: Union[str, None] = "4b7db39b1f81"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
