"""changed street and house to address

Revision ID: dc89f11a094d
Revises: 1c4c66a94d41
Create Date: 2024-03-06 01:26:19.358056

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc89f11a094d"
down_revision: Union[str, None] = "1c4c66a94d41"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "geodatas",
        sa.Column(
            "address", sa.String(), nullable=True
        ),
    )
    op.drop_column("geodatas", "street")
    op.drop_column("geodatas", "house")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "geodatas",
        sa.Column(
            "house",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "geodatas",
        sa.Column(
            "street",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("geodatas", "address")
    # ### end Alembic commands ###
