"""changed company to cafe

Revision ID: e36378dc88cf
Revises: dc89f11a094d
Create Date: 2024-03-06 01:41:33.611001

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e36378dc88cf"
down_revision: Union[str, None] = "dc89f11a094d"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cafes",
        sa.Column(
            "company_name",
            sa.String(),
            nullable=False,
        ),
    )
    op.drop_constraint(
        "cafes_company_id_fkey",
        "cafes",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "cafes",
        "companies",
        ["company_name"],
        ["name"],
    )
    op.drop_column("cafes", "company_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cafes",
        sa.Column(
            "company_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        None, "cafes", type_="foreignkey"
    )
    op.create_foreign_key(
        "cafes_company_id_fkey",
        "cafes",
        "companies",
        ["company_id"],
        ["id"],
    )
    op.drop_column("cafes", "company_name")
    # ### end Alembic commands ###
