"""removing indicies

Revision ID: fa55372562d1
Revises: b3043da7ae4c
Create Date: 2024-03-08 23:37:26.584192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa55372562d1"
down_revision: Union[str, None] = "b3043da7ae4c"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_cities_name", table_name="cities"
    )
    op.create_unique_constraint(
        None, "cities", ["name"]
    )
    op.drop_index(
        "ix_geodatas_city_id",
        table_name="geodatas",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_geodatas_city_id",
        "geodatas",
        ["city_id"],
        unique=False,
    )
    op.drop_constraint(
        None, "cities", type_="unique"
    )
    op.create_index(
        "ix_cities_name",
        "cities",
        ["name"],
        unique=True,
    )
    # ### end Alembic commands ###
